import React from 'react'
import Head from 'next/head'
import { Children } from '../types/children'

export const Layout = ({ children }: Children): JSX.Element => {
    return (
        <>
            <Head>
                <title>PROJECT_NAME_HERE</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {children}
        </>
    )
}
